### PR TITLE
add *FIT_HEIGHT* and *FIT_WIDTH* DisplayTypes

### PR DESCRIPTION
**Pull request by sumit-anantwar**
We are using this library in our production code and we need the below DisplayTypes.
And we believe that adding this functionality will surely add value to an already amazing library.

*FIT_HEIGHT* : The image fits such that the Image height matches the device height. Generally useful in portrait orientation.
*FIT_WIDTH* : The image fits such that the Image width matches the device width. Generally useful in landscape orientation.

P.S. :  We have also updated the gradle files and have made sure that the builds pass on Travis.

### CODE REVIEW

**Comment by sumit-anantwar** [comment]
Hi, because we need this functionality in our production code, we would be really grateful if you could review and accept this pull request.

**Comment by sumit-anantwar** [comment]
Thanks a lot!
Do please let us know when the updates would be published on JCenter

**Comment by sephiroth74** [comment]
I’ve just uploaded the snapshot version.
Let me know if it’s ok, then I’ll publish the release.
https://oss.sonatype.org/content/repositories/snapshots/it/sephiroth/android/library/imagezoom/imagezoom/2.3.0-SNAPSHOT/

-
Alessandro Crugnola
Adobe System Inc
Photoshop Android Engineering Lead

100-104 Fifth Ave.
New York, NY 10011

**Comment by sumit-anantwar** [comment]
Works perfectly!
Appreciate the quick response.
Thanks again.

**Pull request merged**
